### ISSUE TITLE
Change 5GHz channel to a DFS channel

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmeshfeed#14]
Our default channel 165 is overused. There's too much interference.

I think we should change the default channel to a DFS channel. It Makes a huge difference in speed, due to lack of interference. I've been using 124. Should probably use one that Link NYC isn't using so much.

**Comment by jedahan** [comment]
Don't we need to have something that disables DFS when needed? Like we listen for a DFS beacon, and turn it off?

**Comment by bhny** [comment]
NanoStations are FCC compliant, wouldn't they do this automatically in hardware?

**Comment by sycophantic** [comment]
Wouldn't there be a risk of it changing channels if radar is detected? Does the I'm getting scan for the backbone mesh network if the channel changes?

**Comment by bhny** [comment]
Hm, couldn't find much by googling. It seems that the NSM5 does a scan on startup to make sure the DFS channel is free. Not sure how this works with OpenWrt. All the Manhattan Link NYC kiosks seem to use DFS. I should email and ask them how that works. I think radar is only a problem near the airports.

**Comment by jedahan** [comment]
I know that portalwifi heavily advertises that they scan DFS not just on startup but during operation in case of emergency. I would love to use DFS but only after testing that we respect the emergency airwaves.

**Comment by bhny** [comment]
Probably not a good idea for default :-(
