### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by johnnagro** [nycmeshnet/nycmeshfeed#6]
Can someone add an appropriate license to this so it is clear how this code is allowed to be used/reused? I'd like to re-use some of this code in another, non-commerical meshnet project. Thanks.

**Comment by sycophantic** [comment]
It's GPL 2, where is it missing from?

**Comment by johnnagro** [comment]
Aha yeah sorry, I was looking for a `LICENSE` file, i see it in `COPYING`. many thanks.
