### ISSUE TITLE
nodogsplash needs latest version

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/nycmeshfeed#8]
Old version has bug where it can't launch until all the interfaces are up. 

We also need to remove scripts that works around this bug.

**Comment by josmo** [comment]
The latest bleeding edge version of qMp seems to include nodogsplash2 which has those fixes. However 4.0 is still based on 1.x . I'll try to take a look to see what direction we want to go. Force include 2.x or starting moving to bleeding edge

**Comment by josmo** [comment]
I'm going to close this and move the discussion to #23 since we're moving to libremesh
